name: popshop
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: "^0.2.7"
  cached_network_image: ^0.8.0
  flutter_pagewise: ^1.2.3
  flutter_map: ^0.6.1+2
  url_launcher: ^5.0.2
  share: ^0.6.1+1
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.5
  path_provider: ^0.5.0+1
  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  stripe_api: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family:  PopshopIcons
    fonts:
    - asset: fonts/PopshopIcons.ttf
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Thin.otf
      weight: 100
    - asset: fonts/Montserrat-ExtraLight.otf
      weight: 200
    - asset: fonts/Montserrat-Light.otf
      weight: 300
    - asset: fonts/Montserrat-Regular.otf
      weight: 400
    - asset: fonts/Montserrat-Medium.otf
      weight: 500
    - asset: fonts/Montserrat-SemiBold.otf
      weight: 600
    - asset: fonts/Montserrat-Bold.otf
      weight: 700
    - asset: fonts/Montserrat-ExtraBold.otf
      weight: 800
    - asset: fonts/Montserrat-Black.otf
      weight: 900
  - family: Muli
    fonts:
    - asset: fonts/Muli-ExtraLight.ttf
      weight: 100
    - asset: fonts/Muli-Light.ttf
      weight: 300
    - asset: fonts/Muli-Regular.ttf
      weight: 400
    - asset: fonts/Muli-SemiBold.ttf
      weight: 700
    - asset: fonts/Muli-Bold.ttf
      weight: 900